[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bumpin_trade = "GhzHdLjZ1qLLPnPq6YdeqJAszuBRN8WnLnK455yBbig6"
#bumpin_trade = "m3CNxDRMvfVAn1fBxceL6wdcy9srHfR9qQFvxyDPPJd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
