[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
bumpin_trade = "CJybzCuwnwjR8QNsv5jEjxS6H8C1kDYrsXLio5bmx122"

[programs.localnet]
bumpin_trade = "CJybzCuwnwjR8QNsv5jEjxS6H8C1kDYrsXLio5bmx122"
pyth = "GA1yvLBfF9Tj5q89CJg7ixNHDrfEMmkXTbM7CgN2bakF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
#cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000"
testall = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
