[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
bumpin_trade = "2yBLUGR3kEeTTym6KvkVjrnkMn9snMjd43hoUqovQgDT"

[programs.localnet]
bumpin_trade = "2yBLUGR3kEeTTym6KvkVjrnkMn9snMjd43hoUqovQgDT"
pyth = "HDk9ZaYCYQrttm5j8v8T87aZks3XEczQXsN9MHj5XsBx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
#cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000"
testall = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
