[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
bumpin_trade = "B1iAhByrb5SaGooKa4DdNGdCLCsVweCfWcT3MvLxQJXt"

[programs.localnet]
bumpin_trade = "B1iAhByrb5SaGooKa4DdNGdCLCsVweCfWcT3MvLxQJXt"
pyth = "6GHM4TvoUsUxJp5mHC44TBmx8J5gTSQUHEtJgBvHWWXP"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Devnet"
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000"
testall = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
